// ============================================================
// LONGHAUL — Game State & Time System
// Real-time simulation with 3 speed settings
// ============================================================

import { createDefaultShip } from './ship.js';

// Speed multipliers: game-minutes per real-second
const SPEED_MULTIPLIERS = {
  0: 0,     // Paused
  1: 1,     // 1 min per second
  2: 60,    // 1 hour per second
  3: 1440,  // 1 day per second
};

export function createGameState(shipName, captainName, crewCount) {
  const ship = createDefaultShip(crewCount);
  ship.name = shipName;
  ship.crew[0].name = captainName;
  ship.crew[0].role = 'Captain';

  return {
    version: '0.1.1',
    ship,
    // Game time: start date far future
    time: {
      year: 2351,
      month: 3,
      day: 22,
      hour: 8,
      minute: 0,
    },
    speed: 1,
    paused: false,
    resources: {
      fuel: { current: 8500, max: 10000, unit: 'kg' },
      oxygen: { current: 950, max: 1000, unit: 'hr' },
      water: { current: 4200, max: 5000, unit: 'L' },
      food: { current: 1800, max: 2000, unit: 'rations' },
      power: { current: 88, max: 100, unit: '%' },
    },
    navigation: {
      thrust: 0,
      heading: null,
      velocity: 0,
    },
    stats: {
      distanceTraveled: 0,
      daysElapsed: 0,
    },
  };
}

// ---- TIME SYSTEM ----

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

function advanceTime(time, minutes) {
  time.minute += minutes;

  while (time.minute >= 60) {
    time.minute -= 60;
    time.hour++;
  }

  while (time.hour >= 24) {
    time.hour -= 24;
    time.day++;
  }

  while (time.day > DAYS_IN_MONTH[(time.month - 1) % 12]) {
    time.day -= DAYS_IN_MONTH[(time.month - 1) % 12];
    time.month++;
    if (time.month > 12) {
      time.month = 1;
      time.year++;
    }
  }
}

export function formatDate(time) {
  return `${time.year}.${String(time.month).padStart(2, '0')}.${String(time.day).padStart(2, '0')}`;
}

export function formatTime(time) {
  return `${String(time.hour).padStart(2, '0')}:${String(time.minute).padStart(2, '0')}`;
}

// ---- GAME LOOP ----

export class GameLoop {
  constructor(state, onTick) {
    this.state = state;
    this.onTick = onTick;
    this.lastTime = null;
    this.accumulator = 0;
    this.running = false;
    this._raf = null;
  }

  start() {
    this.running = true;
    this.lastTime = performance.now();
    this._tick();
  }

  stop() {
    this.running = false;
    if (this._raf) {
      cancelAnimationFrame(this._raf);
      this._raf = null;
    }
  }

  setSpeed(speed) {
    this.state.speed = speed;
    this.state.paused = speed === 0;
  }

  _tick() {
    if (!this.running) return;

    const now = performance.now();
    const delta = (now - this.lastTime) / 1000; // seconds
    this.lastTime = now;

    if (!this.state.paused && this.state.speed > 0) {
      const gameMinutes = delta * SPEED_MULTIPLIERS[this.state.speed];
      this.accumulator += gameMinutes;

      // Process in whole-minute increments
      while (this.accumulator >= 1) {
        this.accumulator -= 1;
        this._processMinute();
      }
    }

    this.onTick(this.state);
    this._raf = requestAnimationFrame(() => this._tick());
  }

  _processMinute() {
    advanceTime(this.state.time, 1);

    // Resource consumption per game-minute (basic)
    const crewCount = this.state.ship.crew.length;
    const res = this.state.resources;

    // Oxygen: consumed by crew, 1 unit per crew per hour
    res.oxygen.current = Math.max(0, res.oxygen.current - (crewCount / 60));

    // Water: consumed slowly
    res.water.current = Math.max(0, res.water.current - (crewCount * 0.002));

    // Food: consumed at meal times (simplified: steady drain)
    res.food.current = Math.max(0, res.food.current - (crewCount * 0.001));

    // Fuel: consumed only under thrust
    if (this.state.navigation.thrust > 0) {
      res.fuel.current = Math.max(0, res.fuel.current - (this.state.navigation.thrust * 0.05));
    }

    // Power: regenerated by reactor, consumed by systems
    res.power.current = Math.min(res.power.max, res.power.current + 0.001);

    // Track elapsed days
    this.state.stats.daysElapsed += 1 / 1440;
  }
}
